create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  external_id text not null unique,
  title text not null,
  product_url text,
  image_url text,
  category_id text,
  category_name text,
  seller_id text,
  seller_name text,
  warehouse_country text,
  ships_to text[] not null default '{}',
  currency text,
  current_price numeric(12,2),
  original_price numeric(12,2),
  commission_rate numeric(8,4),
  rating numeric(5,2),
  order_count bigint,
  active boolean not null default true,
  raw jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_warehouse_idx on public.products(warehouse_country);
create index if not exists products_active_idx on public.products(active);

create table if not exists public.product_observations (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  observed_at timestamptz not null default now(),
  price numeric(12,2),
  original_price numeric(12,2),
  discount_pct numeric(8,4),
  rating numeric(5,2),
  order_count bigint,
  stock_signal numeric(12,4),
  delivery_days integer,
  seller_score numeric(10,4),
  demand_proxy numeric(14,4),
  trend_proxy numeric(14,4),
  competition_proxy numeric(14,4),
  raw jsonb not null default '{}'::jsonb
);

create index if not exists observations_product_time_idx on public.product_observations(product_id, observed_at desc);

create table if not exists public.demand_features (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  feature_time timestamptz not null default now(),
  momentum_7d numeric(14,6),
  momentum_30d numeric(14,6),
  price_velocity numeric(14,6),
  discount_strength numeric(14,6),
  seller_strength numeric(14,6),
  delivery_strength numeric(14,6),
  competition_score numeric(14,6),
  seasonality_score numeric(14,6),
  trend_score numeric(14,6),
  conversion_signal numeric(14,6),
  feature_vector jsonb not null default '{}'::jsonb,
  model_version text not null default 'features-v1'
);

create index if not exists demand_features_product_time_idx on public.demand_features(product_id, feature_time desc);

create table if not exists public.forecasts (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  generated_at timestamptz not null default now(),
  horizon_days integer not null check (horizon_days in (30,60,90)),
  forecast_demand numeric(16,4) not null,
  lower_bound numeric(16,4),
  upper_bound numeric(16,4),
  confidence numeric(8,6) check (confidence between 0 and 1),
  model_version text not null,
  feature_snapshot jsonb not null default '{}'::jsonb,
  rationale jsonb not null default '{}'::jsonb
);

create index if not exists forecasts_product_horizon_idx on public.forecasts(product_id, horizon_days, generated_at desc);

create table if not exists public.opportunity_scores (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  scored_at timestamptz not null default now(),
  total_score numeric(10,4) not null,
  demand_score numeric(10,4),
  forecast_score numeric(10,4),
  margin_score numeric(10,4),
  competition_score numeric(10,4),
  fulfilment_score numeric(10,4),
  confidence_score numeric(10,4),
  risk_penalty numeric(10,4),
  recommended_action text not null check (recommended_action in ('PROMOTE','WATCH','REJECT')),
  explanation jsonb not null default '{}'::jsonb,
  scoring_version text not null default 'score-v1'
);

create index if not exists opportunity_latest_idx on public.opportunity_scores(scored_at desc, total_score desc);

create table if not exists public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  agent_name text not null,
  run_type text not null,
  status text not null check (status in ('queued','running','succeeded','failed','partial')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms bigint,
  input_count integer not null default 0,
  output_count integer not null default 0,
  error_count integer not null default 0,
  estimated_cost numeric(14,6) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  error jsonb
);

create index if not exists agent_runs_started_idx on public.agent_runs(started_at desc);

create table if not exists public.agent_decisions (
  id bigint generated by default as identity primary key,
  run_id uuid references public.agent_runs(id) on delete set null,
  product_id uuid references public.products(id) on delete cascade,
  agent_name text not null,
  decision text not null,
  confidence numeric(8,6),
  reason_codes text[] not null default '{}',
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agent_decisions_product_idx on public.agent_decisions(product_id, created_at desc);

create table if not exists public.system_config (
  key text primary key,
  value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

insert into public.system_config(key, value, description) values
('target_markets', '["GR"]'::jsonb, 'Destination markets monitored by the system'),
('allowed_warehouse_countries', '["ES","FR","DE","IT","PL","CZ","BE","NL"]'::jsonb, 'Warehouses treated as EU-stock'),
('forecast_horizons', '[30,60,90]'::jsonb, 'Forecast horizons in days'),
('min_confidence', '0.55'::jsonb, 'Minimum confidence before PROMOTE can be recommended'),
('max_delivery_days', '10'::jsonb, 'Maximum configured delivery SLA'),
('score_weights', '{"demand":0.27,"forecast":0.23,"margin":0.14,"competition":0.12,"fulfilment":0.14,"confidence":0.10}'::jsonb, 'Opportunity scoring weights'),
('promotion_threshold', '72'::jsonb, 'Minimum total score for PROMOTE'),
('watch_threshold', '55'::jsonb, 'Minimum total score for WATCH'),
('autonomous_mode', 'true'::jsonb, 'Enables scheduled autonomous evaluation')
on conflict (key) do nothing;

alter table public.products enable row level security;
alter table public.product_observations enable row level security;
alter table public.demand_features enable row level security;
alter table public.forecasts enable row level security;
alter table public.opportunity_scores enable row level security;
alter table public.agent_runs enable row level security;
alter table public.agent_decisions enable row level security;
alter table public.system_config enable row level security;

-- No public policies are created here. Server-side service-role access is expected for autonomous workers.
